## 배열 데이터를 효과적으로 다루는 NumPy
### http://www.numpy.org
#### 다차원 배열 데이터를 효과적으로 치리할수 있다.

In [2]:
import numpy as np

#### 시퀀스 데이터로부터 배열생성 np.array()

In [8]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array([data1])
a1

array([[0, 1, 2, 3, 4, 5]])

In [12]:
data2 = [0, 2.5, 2, 3.5, 4, 8.5]
a2 = np.array(data2)
a2

array([0. , 2.5, 2. , 3.5, 4. , 8.5])

In [13]:
a1.dtype

dtype('int64')

In [14]:
a2.dtype

dtype('float64')

#### 시퀀스 데이터로부터 다차원배열 생성

In [15]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 범위를 지정해 데이터생성 np.arrange(start, end, step)

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

#### 다차원 배열생성 np.arrange().reshape(행,열)

In [20]:
a4 = np.array([5,6,7,8,9,10,11,12,13]).reshape(3,3)
a4

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [24]:
a5 = np.arange(1,7).reshape(3,2)
a5

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 행열 형태확인 .shape

In [21]:
a4.shape

(3, 3)

#### 배열의 시작과 끝 값을 정하고 사이의 데이터 생성 np.linspace()

In [30]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [27]:
np.linspace(1,np.pi,20)

array([1.        , 1.1127154 , 1.22543081, 1.33814621, 1.45086161,
       1.56357701, 1.67629242, 1.78900782, 1.90172322, 2.01443863,
       2.12715403, 2.23986943, 2.35258483, 2.46530024, 2.57801564,
       2.69073104, 2.80344645, 2.91616185, 3.02887725, 3.14159265])

#### 특별한 형태의 배열생성 zeros(), ones(), eye() : 단위행렬

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.eye(8,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

#### 문자열 행렬과 형변환 astype()

In [35]:
a6 = np.array(['1.23','2.6','3.41'])

In [36]:
a6 = a6.astype(float)

In [37]:
a6.astype(int)

array([1, 2, 3])

#### 난수배열생성 np.random.rand(), np.random.randint()

In [40]:
np.random.rand()

0.27395494652314434

In [43]:
np.random.rand(5,5)

array([[0.31090167, 0.21720867, 0.647193  , 0.94938029, 0.72896305],
       [0.70427327, 0.06173235, 0.81117298, 0.3573482 , 0.91159108],
       [0.38750944, 0.39099238, 0.6052085 , 0.14911657, 0.07640125],
       [0.55337329, 0.78680529, 0.77011295, 0.63938589, 0.212255  ],
       [0.46534254, 0.0025675 , 0.92544376, 0.05340557, 0.90642056]])

In [45]:
np.random.randint(10, size=(5,5))

array([[9, 5, 3, 7, 6],
       [3, 5, 6, 0, 6],
       [3, 6, 8, 4, 0],
       [1, 2, 3, 9, 5],
       [3, 2, 6, 8, 8]])

In [47]:
np.random.randint(10, size=(10))

array([4, 2, 5, 4, 2, 6, 4, 9, 3, 8])

#### 배열의 연산

In [48]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10,20,10,20])

In [49]:
arr1 + arr2

array([11, 22, 13, 24])

In [50]:
arr1 - arr2

array([ -9, -18,  -7, -16])

In [51]:
arr1 * arr2

array([10, 40, 30, 80])

In [52]:
arr1 ** arr2

array([            1,       1048576,         59049, 1099511627776])

In [53]:
arr1 / arr2

array([0.1, 0.1, 0.3, 0.2])

In [54]:
arr1 >= arr2

array([False, False, False, False])

#### 통계를 위한 연산
sum() - 합
mean() - 평균
std() - 표준편차
var() - 분산
min() - 최소
max() - 최대
cumsum() - 누적합
cumprod() - 누적곱

In [65]:
arr3 = np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr3.sum()

36

In [58]:
arr3.mean()

4.0

In [59]:
arr3.std()

2.581988897471611

In [60]:
arr3.var()

6.666666666666667

In [61]:
arr3.min()

0

In [62]:
arr3.max()

8

In [63]:
arr3.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [66]:
arr3.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

#### 행렬연산
dot() - 행렬곱
transpose() - 전치행렬
np.linalg.inv() - 역행렬
np.linalg.det() - 행렬식

In [67]:
arr4 = np.array([1,2,3,4]).reshape(2,2)
arr4

array([[1, 2],
       [3, 4]])

In [68]:
arr5 = np.array([1,2,3,4]).reshape(2,2)
arr5

array([[1, 2],
       [3, 4]])

In [69]:
arr4 * arr5

array([[ 1,  4],
       [ 9, 16]])

In [71]:
arr4.dot(arr5)

array([[ 7, 10],
       [15, 22]])

In [72]:
arr4.transpose()

array([[1, 3],
       [2, 4]])

In [73]:
np.linalg.inv(arr4)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [74]:
np.linalg.det(arr4)

-2.0000000000000004

#### 배열 인덱싱과 슬라이싱

In [76]:
a1 = np.array([1,2,3,4,5,6,7])

In [77]:
a1[0]

1

In [78]:
a1[1:3]

array([2, 3])

In [80]:
a1[[1,3,5,6]]

array([2, 4, 6, 7])

In [87]:
a2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a2[2]

array([7, 8, 9])

In [84]:
a2[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [88]:
a2[2] = [4,4,4]
a2

array([[1, 2, 3],
       [4, 5, 6],
       [4, 4, 4]])

In [109]:
a2[[0,2],[1,1]]

array([2, 4])

In [114]:
a2[a2 > 3]

array([4, 5, 6, 4, 4, 4])

In [116]:
a2[a2 % 2 == 0]

array([2, 4, 6, 4, 4, 4])